### ISSUE TITLE
skopeo copy cannot retry when `dest` is a docker-archive

### ISSUE THREAD

**Issue by john-mullaney** [containers/skopeo#1708]
I have a script that runs commands like `skopeo copy --retry-times 3 docker://<my proprietary image> docker-archive:/tmp/tmpqnbak5px/7a4351d9-06c7-11ed-a7e6-0242ac110002`, and it saw an error:

```
Getting image source signatures
[...snip...]
Copying blob 35f7e8050bfc done  
Copying blob fc0c1d26bf77 [================>---------------------] 35.2MiB / 80.7MiB
Copying blob b74c49863c7e done  
WARN[0076] failed, retrying in 1s ... (1/3). Error: Error writing blob: error happened during read: read tcp 172.17.0.2:37318->10.101.130.100:443: read: connection reset by peer 
FATA[0077] Error initializing destination docker-archive:/tmp/tmpqnbak5px/7a4351d9-06c7-11ed-a7e6-0242ac110002: docker-archive doesn't support modifying existing images 
```

It does indicate that it is on retry 1 out of 3, but hits a fatal error because the target archive that was in the process of being saved still exists. The `docker-archive doesn't support modifying existing images` error ultimately comes from https://github.com/containers/image/blob/main/docker/archive/writer.go

I apologize that I am unable to reproduce the `connection reset by peer` issue, but I looked at the code in the underlying [containers/image](https://github.com/containers/image) library, and I believe this current behavior is the expected behavior. That is to say, I believe the problem is that the `image` code that copies to a docker-archive is not aware of the skopeo retry code, and neither `image` nor `skopeo` attempt to clean-up a half-downloaded archive.

**Comment by mtrmac** [comment]
Thanks for your report. You’re right — c/image should be taught about unsuccessful writes to docker-archive, and delete the file in that case.

**Comment by mtrmac** [comment]
… but only if the destination is a regular file, not e.g. a named pipe.

**Comment by djpbessems** [comment]
Facing the same issue.

**Comment by mtrmac** [comment]
Should be fixed by https://github.com/containers/image/pull/1633 .

**Comment by djpbessems** [comment]
When is the next release scheduled that will include this fix?

**Comment by rhatdan** [comment]
Were looking at the week after next.

**Comment by djpbessems** [comment]
I'm still seeing this error with skopeo 1.10.0; was this fix included in a release yet?

**Comment by djpbessems** [comment]
Actually, I just built 1.11.0-dev (from HEAD) and I'm still getting this error.

**Comment by mtrmac** [comment]
@djpbessems This was AFAICT fixed with 1.10.0; with the code manually modified to inject a failure, I can reproduce it with 1.9 and it works with 1.10.

if you see something else, please file a separate report with the failure output and ideally steps to reproduce.

**Comment by djpbessems** [comment]
Oh, sorry for not updating; this was actually entirely my own fault for not noticing my scripting logic was generating the same .tar filename for separate container images. So the error I was receiving was entirely correct.
